name: Setup Rust Environment
description: Install Rust toolchain with caching for build artifacts
inputs:
  components:
    description: Comma-separated list of Rust components to install
    required: false
    default: rustfmt, clippy, llvm-tools-preview
  target:
    description: Target triple to install
    required: false
    default: ''
  cache-key-prefix:
    description: Prefix for cache keys
    required: false
    default: rust-build
  cache-cargo-home:
    description: Whether to cache cargo home directory
    required: false
    default: 'true'
  maximize-build-space:
    description: Whether to maximize build space on Linux (removes .NET, Android, etc.)
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: Whether the Rust cache was restored
    value: ${{ steps.cache-rust.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Maximize build space (Linux only)
      if: runner.os == 'Linux' && inputs.maximize-build-space == 'true'
      shell: bash
      run: |
        echo "Freeing up disk space on Linux runner..."
        # Remove .NET runtime (~17 GB)
        sudo rm -rf /usr/share/dotnet
        # Remove Android SDK (~11 GB)
        sudo rm -rf /usr/local/lib/android
        # Remove Haskell (~2.7 GB)
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        # Remove CodeQL (~5.4 GB)
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        # Remove Docker images (~3 GB)
        docker system prune -af 2>/dev/null || true
        echo "Disk space freed successfully"
        df -h

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: ${{ inputs.components }}
        target: ${{ inputs.target }}

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Configure Rust lint and sccache flags
      shell: bash
      run: |
        set -euo pipefail
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
        echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
        base="${RUSTFLAGS:-"-D warnings -A unpredictable-function-pointer-comparisons"}"
        if ! check_output="$(printf 'fn main() {}\n' | RUSTC_COLOR=never rustc -W fn_ptr_eq - 2>&1)"; then
          :
        fi
        if grep -qi "unknown lint" <<<"$check_output"; then
          echo "fn_ptr_eq lint unavailable on $(rustc -V); skipping flag"
        else
          base+=" -A fn_ptr_eq --cfg has_fn_ptr_eq_lint"
          echo "Detected fn_ptr_eq lint support; appended suppression flags"
        fi
        echo "RUSTFLAGS=$base" >> "$GITHUB_ENV"

    - name: Generate Cargo.lock hash
      id: cargo-hash
      shell: bash
      run: |
        set -euo pipefail
        # Generate hash from Cargo.lock files, with fallback if hashFiles fails
        # Primary: root Cargo.lock (workspace lock file)
        # Works on both Linux (sha256sum) and macOS (shasum -a 256)
        if [ -f "Cargo.lock" ]; then
          if command -v sha256sum &> /dev/null; then
            hash=$(sha256sum Cargo.lock | cut -d' ' -f1)
          elif command -v shasum &> /dev/null; then
            hash=$(shasum -a 256 Cargo.lock | cut -d' ' -f1)
          else
            # Fallback to file modification time if no hash tool available
            hash=$(stat -c %Y Cargo.lock 2>/dev/null || stat -f %m Cargo.lock)
          fi
        else
          # Fallback to a timestamp-based hash if no Cargo.lock exists
          hash=$(date +%Y%m%d)
        fi
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
        echo "Using Cargo.lock hash: $hash"

    - name: Cache Rust build artifacts
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ steps.cargo-hash.outputs.hash }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: Cache cargo-llvm-cov
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-llvm-cov
        key: cargo-llvm-cov-${{ runner.os }}

    - name: Ensure sccache is on PATH
      if: env.SCCACHE_PATH != ''
      shell: bash
      run: echo "${SCCACHE_PATH}" >> "$GITHUB_PATH"

    - name: Install cargo-llvm-cov if not cached
      shell: bash
      run: |
        if ! command -v cargo-llvm-cov &> /dev/null; then
          echo "Installing cargo-llvm-cov..."
          cargo install cargo-llvm-cov
        else
          echo "cargo-llvm-cov already installed"
        fi
