name: Setup Rust Environment
description: Install Rust toolchain with caching for build artifacts
inputs:
  components:
    description: Comma-separated list of Rust components to install
    required: false
    default: rustfmt, clippy, llvm-tools-preview
  target:
    description: Target triple to install
    required: false
    default: ''
  cache-key-prefix:
    description: Prefix for cache keys
    required: false
    default: rust-build
  toolchain:
    description: Specific Rust toolchain triple/channel to install (e.g., stable, stable-x86_64-pc-windows-gnu)
    required: false
    default: ''
  cache-cargo-home:
    description: Whether to cache cargo home directory
    required: false
    default: 'true'
  maximize-build-space:
    description: Whether to maximize build space on Linux (removes .NET, Android, etc.)
    required: false
    default: 'true'
  use-sccache:
    description: Enable sccache as the Rust compiler wrapper
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: Whether the Rust cache was restored
    value: ${{ steps.cache-rust.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Maximize build space (Linux only)
      if: runner.os == 'Linux' && inputs.maximize-build-space == 'true'
      shell: bash
      run: |
        echo "Freeing up disk space on Linux runner..."
        # Remove .NET runtime (~17 GB)
        sudo rm -rf /usr/share/dotnet
        # Remove Android SDK (~11 GB)
        sudo rm -rf /usr/local/lib/android
        # Remove Haskell (~2.7 GB)
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        # Remove CodeQL (~5.4 GB)
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        # Remove Docker images (~3 GB)
        docker system prune -af 2>/dev/null || true
        echo "Disk space freed successfully"
        df -h

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        target: ${{ inputs.target }}

    - name: Setup sccache
      if: inputs.use-sccache == 'true'
      uses: mozilla-actions/sccache-action@v0.0.9
      continue-on-error: true

    - name: Configure Rust flags
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.use-sccache }}" = "true" ]; then
          # Check if sccache is actually available before enabling it
          if command -v sccache &> /dev/null; then
            echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
            echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
            echo "sccache is available, enabling as RUSTC_WRAPPER"
          else
            echo "SCCACHE_GHA_ENABLED=false" >> "$GITHUB_ENV"
            echo "RUSTC_WRAPPER=" >> "$GITHUB_ENV"
            echo "Warning: sccache requested but not found, proceeding without it"
          fi
        else
          echo "SCCACHE_GHA_ENABLED=false" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=" >> "$GITHUB_ENV"
        fi
        base="${RUSTFLAGS:-"-D warnings -A unpredictable-function-pointer-comparisons"}"
        if [ "${{ inputs.target }}" = "wasm32-unknown-unknown" ]; then
          base+=" -C target-feature=+atomics,+bulk-memory"
          base+=" -C link-arg=--shared-memory"
          base+=" -C link-arg=--max-memory=2147483648"
          base+=" -C link-arg=--import-memory"
          base+=" -C link-arg=--export=__wasm_init_tls"
          base+=" -C link-arg=--export=__tls_size"
          base+=" -C link-arg=--export=__tls_align"
          base+=" -C link-arg=--export=__tls_base"
        fi
        if ! check_output="$(printf 'fn main() {}\n' | RUSTC_COLOR=never rustc -W fn_ptr_eq - 2>&1)"; then
          :
        fi
        if grep -qi "unknown lint" <<<"$check_output"; then
          echo "fn_ptr_eq lint unavailable on $(rustc -V); skipping flag"
        else
          base+=" -A fn_ptr_eq --cfg has_fn_ptr_eq_lint"
          echo "Detected fn_ptr_eq lint support; appended suppression flags"
        fi
        echo "RUSTFLAGS=$base" >> "$GITHUB_ENV"

    - name: Generate Cargo.lock hash
      id: cargo-hash
      shell: bash
      run: |
        set -euo pipefail
        # Generate hash from Cargo.lock files, with fallback if hashFiles fails
        # Primary: root Cargo.lock (workspace lock file)
        # Works on both Linux (sha256sum) and macOS (shasum -a 256)
        if [ -f "Cargo.lock" ]; then
          if command -v sha256sum &> /dev/null; then
            hash=$(sha256sum Cargo.lock | cut -d' ' -f1)
          elif command -v shasum &> /dev/null; then
            hash=$(shasum -a 256 Cargo.lock | cut -d' ' -f1)
          else
            # Fallback to file modification time if no hash tool available
            hash=$(stat -c %Y Cargo.lock 2>/dev/null || stat -f %m Cargo.lock)
          fi
        else
          # Fallback to a timestamp-based hash if no Cargo.lock exists
          hash=$(date +%Y%m%d)
        fi
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
        echo "Using Cargo.lock hash: $hash"

    - name: Cache Rust build artifacts
      id: cache-rust
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ inputs.cache-key-prefix }}-v3-${{ runner.os }}-${{ inputs.target || 'default' }}-${{ steps.cargo-hash.outputs.hash }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-v3-${{ runner.os }}-${{ inputs.target || 'default' }}-

    - name: Cache cargo-llvm-cov
      uses: actions/cache@v5
      with:
        path: ~/.cargo/bin/cargo-llvm-cov
        key: cargo-llvm-cov-v2-${{ runner.os }}

    - name: Validate sccache installation
      if: inputs.use-sccache == 'true'
      shell: bash
      run: |
        set +e  # Don't exit on error for diagnostics
        echo "Checking sccache installation..."
        if command -v sccache &> /dev/null; then
          echo "sccache found in PATH"
          which sccache
          sccache --version || echo "sccache version check failed"
        elif [ -n "${SCCACHE_PATH:-}" ] && [ -d "${SCCACHE_PATH}" ]; then
          echo "SCCACHE_PATH is set to: ${SCCACHE_PATH}"
          if [ -f "${SCCACHE_PATH}/sccache" ]; then
            echo "sccache executable found at SCCACHE_PATH"
            "${SCCACHE_PATH}/sccache" --version || echo "sccache version check failed"
          else
            echo "sccache executable NOT found at SCCACHE_PATH"
            ls -la "${SCCACHE_PATH}" || echo "Failed to list SCCACHE_PATH contents"
          fi
        else
          echo "Warning: sccache not found in PATH and SCCACHE_PATH not set or invalid"
          echo "Continuing without sccache"
        fi
        set -e

    - name: Ensure sccache is on PATH
      if: inputs.use-sccache == 'true' && env.SCCACHE_PATH != ''
      shell: bash
      run: |
        if [ -d "${SCCACHE_PATH}" ] && [ -f "${SCCACHE_PATH}/sccache" ]; then
          echo "${SCCACHE_PATH}" >> "$GITHUB_PATH"
          echo "Added sccache to PATH"
        else
          echo "Warning: sccache not available at ${SCCACHE_PATH}, proceeding without sccache"
        fi

    - name: Install cargo-llvm-cov if not cached
      shell: bash
      run: |
        if ! command -v cargo-llvm-cov &> /dev/null; then
          echo "Installing cargo-llvm-cov..."
          cargo install cargo-llvm-cov
        else
          echo "cargo-llvm-cov already installed"
        fi
