version: "3"
vars:
  RUST_LOG: info
  V3_TAG: v3.20.2
  BUNDLE: bundle
  GOLANGCI_LINT_VERSION: v2.6.2
silent: false
tasks:
  sync-versions:
    desc: Sync version from Cargo.toml to all package manifests
    cmds:
      - uv run python scripts/sync_versions.py
  setup:
    desc: Install dependencies for all languages
    cmds:
      - task: python:install
      - task: typescript:install
      - task: ruby:install
      - task: java:install
      - task: go:install
      - task: rust:build
  build:
    desc: Build core libraries and language bindings
    cmds:
      - task: rust:build
      - task: python:build
      - task: ruby:build
      - task: typescript:build
      - task: java:build
  test:
    desc: Run test suites for all languages
    cmds:
      - task: rust:test
      - task: python:test
      - task: ruby:test
      - task: typescript:test
      - task: java:test
      - task: go:test
  lint:
    desc: Run linters for all languages
    cmds:
      - task: rust:check
      - task: python:lint
      - task: go:lint
      - task: ruby:lint
      - task: typescript:lint
      - task: java:lint
  format:
    desc: Format code for all languages
    cmds:
      - task: rust:format
      - task: python:format
      - task: ruby:format
      - task: typescript:format
  rust:build:
    desc: Build all Rust crates
    cmds:
      - cargo build --release --workspace
  rust:test:
    desc: Run all Rust tests
    cmds:
      - cargo test --workspace --release
  rust:check:
    desc: Check Rust code
    cmds:
      - cargo check --workspace
      - cargo clippy --workspace -- -D warnings
  rust:format:
    desc: Format Rust code
    cmds:
      - cargo fmt --all
  rust:doc:
    desc: Generate Rust documentation
    cmds:
      - cargo doc --no-deps --open
  rust:update:
    desc: Update Rust dependencies
    cmds:
      - echo "Updating Rust dependencies..."
      - cargo upgrade --incompatible
      - cargo update
  python:install:
    desc: Install Python dependencies
    dir: packages/python
    cmds:
      - uv sync --all-extras --no-install-workspace
  python:test:
    desc: Run Python tests
    dir: packages/python
    cmds:
      - uv run pytest
  python:test:coverage:
    desc: Run Python tests with coverage
    dir: packages/python
    cmds:
      - uv run pytest --cov --cov-report=html
  python:lint:
    desc: Lint Python code
    dir: packages/python
    cmds:
      - uv run ruff check
      - uv run ruff format --check
      - uv run mypy
  python:format:
    desc: Format Python code
    dir: packages/python
    cmds:
      - uv run ruff check --fix
      - uv run ruff format
  python:build:
    desc: Build Python wheel
    dir: packages/python
    cmds:
      - maturin develop --release
  python:update:
    desc: Update Python dependencies
    cmds:
      - echo "Updating Python dependencies..."
      - uv run uv-bump --pyproject-toml pyproject.toml
      - uv run uv-bump --pyproject-toml packages/python/pyproject.toml
      - uv run uv-bump --pyproject-toml v3/pyproject.toml
      - uv sync --all-packages --all-extras --upgrade --no-install-workspace
  ruby:install:
    desc: Install Ruby dependencies
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} install"
  ruby:build:
    desc: Build Ruby extension
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rake compile"
  ruby:update:
    desc: Update Ruby dependencies
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} update"
  ruby:test:
    desc: Run Ruby tests
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rspec"
  ruby:test:verbose:
    desc: Run Ruby tests with detailed output
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rspec --format documentation --color"
  ruby:lint:
    desc: Lint Ruby code (rubocop + steep type checking)
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rubocop"
      - "{{.BUNDLE}} exec steep check"
  ruby:lint:fix:
    desc: Auto-fix Ruby lint issues
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rubocop --autocorrect-all"
  ruby:format:
    desc: Format Ruby code
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rubocop --autocorrect-all"
  ruby:typecheck:
    desc: Run steep type checking
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec steep check"
  ruby:console:
    desc: Open Ruby console with Kreuzberg loaded
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec pry -r ./lib/kreuzberg"
  typescript:install:
    desc: Install TypeScript dependencies
    dir: packages/typescript
    cmds:
      - pnpm install
  typescript:build:
    desc: Build TypeScript package
    dir: packages/typescript
    cmds:
      - pnpm build
  typescript:test:
    desc: Run TypeScript tests
    dir: packages/typescript
    cmds:
      - pnpm test
  typescript:lint:
    desc: Lint TypeScript code
    dir: packages/typescript
    cmds:
      - pnpm lint
  typescript:format:
    desc: Format TypeScript code
    dir: packages/typescript
    cmds:
      - pnpm format
  typescript:update:
    desc: Update TypeScript dependencies
    cmds:
      - echo "Updating TypeScript dependencies..."
      - pnpm up --latest -r
  java:install:
    desc: Install Java dependencies
    dir: packages/java
    cmds:
      - mvn clean install -DskipTests
  java:build:
    desc: Build Java package
    dir: packages/java
    cmds:
      - mvn clean package -DskipTests
  java:test:
    desc: Run Java tests
    dir: packages/java
    cmds:
      - mvn test
  java:lint:
    desc: Lint Java code (checkstyle + PMD)
    dir: packages/java
    cmds:
      - mvn checkstyle:check
      - mvn pmd:check pmd:cpd-check
  java:update:
    desc: Update Java dependencies
    dir: packages/java
    cmds:
      - echo "Checking for dependency updates..."
      - mvn versions:display-dependency-updates
      - mvn versions:display-plugin-updates
  e2e:rust:generate:
    desc: Generate Rust E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang rust --fixtures fixtures
        --output e2e
  e2e:rust:format:
    desc: Format generated Rust E2E sources
    cmds:
      - cargo fmt --manifest-path e2e/rust/Cargo.toml
  e2e:rust:lint:
    desc: Lint Rust E2E crate with clippy
    cmds:
      - cargo clippy -p e2e-rust -- -D warnings
  e2e:rust:test:
    desc: Run Rust E2E tests
    cmds:
      - cargo test -p e2e-rust --release
  e2e:rust:verify:
    desc: Regenerate and validate Rust E2E suite (generate + format + lint + test)
    cmds:
      - task: e2e:rust:generate
      - task: e2e:rust:format
      - task: e2e:rust:lint
      - task: e2e:rust:test
  e2e:python:generate:
    desc: Generate Python E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang python --fixtures fixtures
        --output e2e
  e2e:python:lint:
    desc: Lint generated Python E2E suite (ruff + mypy)
    dir: packages/python
    cmds:
      - uv run ruff check ../../e2e/python/tests
      - uv run ruff format ../../e2e/python/tests
      - uv run ruff format --check ../../e2e/python/tests
      - uv run mypy ../../e2e/python/tests
  e2e:python:test:
    desc: Run Python E2E tests
    dir: packages/python
    cmds:
      - uv run pytest ../../e2e/python/tests
  e2e:python:verify:
    desc: Regenerate and validate Python E2E suite (generate + lint + test)
    cmds:
      - task: e2e:python:generate
      - task: e2e:python:lint
      - task: e2e:python:test
  e2e:ts:generate:
    desc: Generate TypeScript E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang typescript --fixtures
        fixtures --output e2e
      - pnpm biome format --write e2e/typescript/tests
      - pnpm biome check e2e/typescript/tests
  e2e:ts:lint:
    desc: Lint generated TypeScript E2E suite (biome)
    cmds:
      - pnpm biome format --write e2e/typescript/tests
      - pnpm biome check e2e/typescript/tests
  e2e:ts:test:
    desc: Run TypeScript E2E tests
    dir: packages/typescript
    cmds:
      - pnpm --filter kreuzberg-node build
      - pnpm vitest run --root ../../e2e/typescript/tests
  e2e:ts:verify:
    desc: Regenerate and validate TypeScript E2E suite (generate + lint + test)
    cmds:
      - task: e2e:ts:generate
      - task: e2e:ts:lint
      - task: e2e:ts:test
  e2e:ruby:generate:
    desc: Generate Ruby E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang ruby --fixtures fixtures --output e2e
  e2e:ruby:lint:
    desc: Lint generated Ruby E2E suite
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rubocop ../../e2e/ruby/spec"
  e2e:ruby:test:
    desc: Run Ruby E2E tests
    dir: packages/ruby
    cmds:
      - "{{.BUNDLE}} exec rspec ../../e2e/ruby/spec"
  e2e:ruby:verify:
    desc: Regenerate and validate Ruby E2E suite (generate + lint + test)
    cmds:
      - task: e2e:ruby:generate
      - task: e2e:ruby:lint
      - task: e2e:ruby:test
  e2e:java:generate:
    desc: Generate Java E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang java --fixtures fixtures --output e2e
  e2e:java:test:
    desc: Run Java E2E tests
    dir: e2e/java
    cmds:
      - mvn test
  e2e:java:verify:
    desc: Regenerate and validate Java E2E suite
    cmds:
      - task: java:build
      - task: e2e:java:generate
      - task: e2e:java:test
  e2e:go:generate:
    desc: Generate Go E2E tests from fixtures
    cmds:
      - cargo run -p kreuzberg-e2e-generator -- generate --lang go --fixtures fixtures --output e2e
      - cmd: |
          cd e2e/go
          gofmt -w .
  e2e:go:test:
    desc: Run Go E2E tests
    dir: e2e/go
    cmds:
      - |
        DYLD_LIBRARY_PATH=../../target/release:${DYLD_LIBRARY_PATH:-} \
        LD_LIBRARY_PATH=../../target/release:${LD_LIBRARY_PATH:-} \
        go test ./...
  e2e:go:verify:
    desc: Regenerate and validate Go E2E suite
    cmds:
      - task: e2e:go:generate
      - task: e2e:go:test
  cli:build:
    desc: Build CLI binary
    cmds:
      - cargo build --release --package kreuzberg-cli
  cli:install:
    desc: Install CLI binary
    cmds:
      - cargo install --path crates/kreuzberg-cli
  dev:install:
    desc: Install all dependencies
    cmds:
      - task: setup
  dev:test:
    desc: Run all tests
    cmds:
      - task: test
  dev:lint:
    desc: Lint all code
    cmds:
      - task: lint
  dev:format:
    desc: Format all code
    cmds:
      - task: format
  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - prek install
      - prek install --hook-type commit-msg
  pre-commit:run:
    desc: Run pre-commit on all files
    cmds:
      - prek run --all-files
  docs:build:
    desc: Build documentation
    cmds:
      - uv run mkdocs build --clean --strict
  docs:serve:
    desc: Serve documentation locally
    cmds:
      - uv run mkdocs serve
  docs:serve:versioned:
    desc: Serve versioned documentation with mike
    cmds:
      - uv run mike serve
  docs:deploy:v4:
    desc: Deploy v4 documentation with mike
    cmds:
      - uv run mike deploy --update-aliases 4.0 latest
      - uv run mike set-default latest
  docs:deploy:v3:
    desc: Deploy v3 documentation from tagged release
    cmds:
      - echo "Creating git worktree for v3 docs ({{.V3_TAG}})..."
      - git worktree remove --force /tmp/kreuzberg-v3-build 2>/dev/null || true
      - git worktree add /tmp/kreuzberg-v3-build {{.V3_TAG}}
      - echo "Disabling social plugin (requires cairo)..."
      - "sed -i.bak 's/^  - social$/  # - social/' /tmp/kreuzberg-v3-build/mkdocs.yaml"
      - echo "Building and deploying v3 docs..."
      - cd /tmp/kreuzberg-v3-build && uv sync --group docs --no-install-workspace && uv pip install mike
      - cd /tmp/kreuzberg-v3-build && uv run mike deploy 3.0 v3
      - echo "Cleaning up worktree..."
      - git worktree remove --force /tmp/kreuzberg-v3-build || true
  docs:deploy:all:
    desc: Deploy both v3 and v4 documentation
    cmds:
      - task: docs:deploy:v4
      - task: docs:deploy:v3
  docs:publish:
    desc: Publish documentation to GitHub Pages
    cmds:
      - uv run mike deploy --push 4.0 latest
  update:
    desc: Update all dependencies to latest versions
    cmds:
      - task: rust:update
      - task: typescript:update
      - task: ruby:update
      - task: python:update
      - task: java:update
      - task: go:update
      - prek autoupdate
      - "echo \"\u2713 All dependencies updated\""
  clean:rust:
    desc: Clean Rust build artifacts
    cmds:
      - cargo clean
  clean:python:
    desc: Clean Python build artifacts
    dir: packages/python
    cmds:
      - rm -rf build/ dist/ *.egg-info .pytest_cache .ruff_cache .mypy_cache
  clean:ruby:
    desc: Clean Ruby build artifacts
    dir: packages/ruby
    cmds:
      - rm -rf lib/*.bundle lib/*.so pkg/ tmp/
  clean:typescript:
    desc: Clean TypeScript build artifacts
    dir: packages/typescript
    cmds:
      - rm -rf dist/ node_modules/
  clean:java:
    desc: Clean Java build artifacts
    dir: packages/java
    cmds:
      - mvn clean
  clean:
    desc: Clean all build artifacts
    cmds:
      - task: clean:rust
      - task: clean:python
      - task: clean:ruby
      - task: clean:typescript
      - task: clean:java
  go:install:
    desc: Install Go tools and modules
    cmds:
      - |
        echo "Installing golangci-lint v{{.GOLANGCI_LINT_VERSION}}..."
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v{{.GOLANGCI_LINT_VERSION}}
      - cmd: |
          cd packages/go
          go mod download
          go mod tidy

  go:update:
    desc: Update Go dependencies and linters
    cmds:
      - |
        echo "Updating golangci-lint to v{{.GOLANGCI_LINT_VERSION}}..."
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v{{.GOLANGCI_LINT_VERSION}}
      - cmd: |
          cd packages/go
          go get -u ./...
          go mod tidy

  go:lint:
    desc: Lint Go bindings
    dir: packages/go
    cmds:
      - go fmt ./...
      - golangci-lint run --config ../../.golangci.yml ./...

  go:test:
    desc: Run Go tests
    dir: packages/go
    cmds:
      - bash ../../scripts/download_pdfium_runtime.sh
      - |
        export LD_LIBRARY_PATH="$PWD/../../target/release:${LD_LIBRARY_PATH:-}"
        export DYLD_FALLBACK_LIBRARY_PATH="$PWD/../../target/release:${DYLD_FALLBACK_LIBRARY_PATH:-}"
        go test ./...

  smoke:node:
    desc: Run Node smoke test locally (require KREUZBERG_NODE_SPEC=file:/abs/path/to/kreuzberg-node.tgz)
    dir: e2e/smoke/node
    cmds:
      - |
        : "${KREUZBERG_NODE_SPEC:?Set KREUZBERG_NODE_SPEC=file:/abs/path/to/kreuzberg-node.tgz}"
        node ../../.github/actions/smoke-node/update-package-spec.js
        rm -f pnpm-lock.yaml
        pnpm install --no-frozen-lockfile
        pnpm run check
