name: Smoke test Python package
description: Tests Python wheel installation and functionality

inputs:
  wheel-path:
    description: Path to the Python wheel file or directory containing wheels
    required: false
    default: ""
  python-version:
    description: Python version to use for testing (e.g., "3.10")
    required: false
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Smoke test Python wheel
      shell: bash
      run: |
        set -euo pipefail
        tmp=$(mktemp -d)
        cp -R e2e/smoke/python/. "$tmp"/
        pushd "$tmp" >/dev/null

        python -m venv .venv
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          VENV_PY=".venv/Scripts/python.exe"
        else
          VENV_PY=".venv/bin/python"
        fi

        pdfium_runtime=""
        if [[ -n "${KREUZBERG_PDFIUM_PREBUILT:-}" ]]; then
          pdfium_runtime="$tmp/pdfium-runtime"
          mkdir -p "$pdfium_runtime"
          case "${RUNNER_OS:-Linux}" in
            Windows)
              src="$KREUZBERG_PDFIUM_PREBUILT/bin/pdfium.dll"
              filename="pdfium.dll"
              ;;
            macOS)
              src="$KREUZBERG_PDFIUM_PREBUILT/lib/libpdfium.dylib"
              filename="libpdfium.dylib"
              ;;
            Linux)
              src="$KREUZBERG_PDFIUM_PREBUILT/lib/libpdfium.so"
              filename="libpdfium.so"
              ;;
            *)
              echo "Unsupported RUNNER_OS '${RUNNER_OS:-}' for Pdfium staging" >&2
              exit 1
              ;;
          esac

          if [[ ! -f "$src" ]]; then
            echo "Pdfium runtime not found at $src" >&2
            exit 1
          fi

          dest="$pdfium_runtime/$filename"
          cp -f "$src" "$dest"

          case "${RUNNER_OS:-Linux}" in
            Windows)
              scripts_dir=$(dirname "$VENV_PY")
              cp -f "$dest" "$scripts_dir/$filename"
              ;;
            macOS)
              export DYLD_LIBRARY_PATH="$pdfium_runtime:${DYLD_LIBRARY_PATH:-}"
              ;;
            Linux)
              export LD_LIBRARY_PATH="$pdfium_runtime:${LD_LIBRARY_PATH:-}"
              ;;
          esac
        fi

        "$VENV_PY" -m pip install --upgrade pip

        if [[ -n "${{ inputs.wheel-path }}" ]]; then
          # Resolve to absolute path if relative
          if [[ "${{ inputs.wheel-path }}" == /* ]]; then
            wheel_path="${{ inputs.wheel-path }}"
          else
            wheel_path="${GITHUB_WORKSPACE}/${{ inputs.wheel-path }}"
          fi

          echo "Looking for wheels in: $wheel_path"

          # If wheel-path is a directory, find the wheel
          if [[ -d "$wheel_path" ]]; then
            wheel_file=$(find "$wheel_path" -name "*.whl" -type f | head -n 1)
            if [[ -z "$wheel_file" ]]; then
              echo "No wheel found in $wheel_path" >&2
              ls -la "$wheel_path" >&2 || true
              exit 1
            fi
            echo "Installing wheel: $wheel_file"
            "$VENV_PY" -m pip install "$wheel_file"
          elif [[ -f "$wheel_path" ]]; then
            echo "Installing wheel: $wheel_path"
            "$VENV_PY" -m pip install "$wheel_path"
          else
            echo "Wheel path does not exist: $wheel_path" >&2
            exit 1
          fi
        else
          # Install from source
          "$VENV_PY" -m pip install "${GITHUB_WORKSPACE}/packages/python"
        fi

        # Run comprehensive smoke tests from E2E suite
        echo "Running comprehensive smoke tests..."
        "$VENV_PY" -m pip install pytest

        # Copy fixtures and smoke tests from E2E
        cp -R "${GITHUB_WORKSPACE}/fixtures" "$tmp"/
        cp -R "${GITHUB_WORKSPACE}/e2e/python/tests" "$tmp"/

        # Run only smoke tests (test_smoke.py)
        "$VENV_PY" -m pytest tests/test_smoke.py -v

        popd >/dev/null
        echo "✓ Python package smoke test passed (7 comprehensive tests)"
