name: Install System Dependencies
description: Install platform specific dependencies required for document conversion
runs:
  using: composite
  steps:
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -eo pipefail
        echo "Updating Homebrew..."
        brew update || true
        echo "Installing pandoc, tesseract, and LibreOffice..."
        brew install pandoc tesseract || brew upgrade pandoc tesseract || true
        brew install --cask libreoffice || brew upgrade --cask libreoffice || true
        echo "Installed packages:"
        brew list pandoc tesseract
        tesseract --version
        echo "Verifying LibreOffice installation..."
        if ! soffice --version; then
          echo "Warning: soffice not available in PATH" >&2
        fi

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eo pipefail
        sudo apt-get update
        sudo apt-get install -y \
          pandoc \
          libreoffice \
          libreoffice-writer \
          libreoffice-calc \
          libreoffice-impress \
          tesseract-ocr \
          tesseract-ocr-eng \
          tesseract-ocr-deu \
          fonts-liberation \
          fonts-dejavu-core \
          fonts-noto-core \
          libssl-dev \
          pkg-config
        echo "Verifying Linux installations..."
        pandoc --version
        soffice --version
        tesseract --version
        echo "Testing LibreOffice headless mode..."
        soffice --headless --version || echo "Warning: LibreOffice headless version check failed"

    - name: Cache LibreOffice (Windows)
      if: runner.os == 'Windows'
      id: cache-libreoffice-windows
      uses: actions/cache@v4
      with:
        path: C:\Program Files\LibreOffice
        key: libreoffice-windows-${{ runner.os }}-v1

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # Check if LibreOffice is already cached
        $libreofficeInstalled = Test-Path "C:\Program Files\LibreOffice\program\soffice.exe"

        if (-not $libreofficeInstalled) {
          Write-Host "Installing pandoc, tesseract, and LibreOffice from chocolatey..."
          choco install -y pandoc tesseract libreoffice --no-progress
        } else {
          Write-Host "LibreOffice found in cache, skipping installation"
          Write-Host "Installing pandoc and tesseract..."
          choco install -y pandoc tesseract --no-progress
        }

        Write-Output "C:\Program Files\Pandoc" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output "C:\Program Files\LibreOffice\program" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output "C:\Program Files\Tesseract-OCR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "C:\Program Files\Pandoc;C:\Program Files\LibreOffice\program;C:\Program Files\Tesseract-OCR;" + $env:PATH

        # Install python-magic-bin for Windows compatibility
        python -m pip install python-magic-bin

        pandoc --version
        soffice --version
        tesseract --version
