name: Install System Dependencies
description: Install platform specific dependencies required for document conversion
runs:
  using: composite
  steps:
    - name: Cache Tesseract data (macOS)
      if: runner.os == 'macOS'
      id: cache-tesseract-macos
      uses: actions/cache@v4
      with:
        path: /usr/local/opt/tesseract/share/tessdata/
        key: tesseract-data-${{ runner.os }}-v2
        restore-keys: |
          tesseract-data-${{ runner.os }}-

    - name: Cache LibreOffice (macOS)
      if: runner.os == 'macOS'
      id: cache-libreoffice-macos
      uses: actions/cache@v4
      with:
        path: /Applications/LibreOffice.app
        key: libreoffice-${{ runner.os }}-v2

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -eo pipefail
        echo "Installing tesseract and LibreOffice..."

        # Install packages only if not already present
        brew list tesseract &>/dev/null || brew install tesseract
        # Add extra tessdata languages needed by tests
        brew list tesseract-lang &>/dev/null || brew install tesseract-lang

        # LibreOffice: skip install if already present on runner/cache to avoid cask error
        if [ -d "/Applications/LibreOffice.app" ]; then
          echo "LibreOffice already present at /Applications/LibreOffice.app, skipping install"
        else
          brew list --cask libreoffice &>/dev/null || brew install --cask libreoffice
        fi
        echo "Installed packages:"
        brew list tesseract
        tesseract --version
        echo "Verifying LibreOffice installation..."
        if ! soffice --version; then
          echo "Warning: soffice not available in PATH" >&2
        fi

    - name: Cache Tesseract data (Linux)
      if: runner.os == 'Linux'
      id: cache-tesseract-linux
      uses: actions/cache@v4
      with:
        path: |
          /usr/share/tesseract-ocr/5/tessdata/
          /usr/share/tesseract-ocr/tessdata/
        key: tesseract-data-linux-v2
        restore-keys: |
          tesseract-data-linux-

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eo pipefail
        sudo apt-get update

        # Build list of packages
        PACKAGES="libreoffice libreoffice-writer libreoffice-calc libreoffice-impress tesseract-ocr tesseract-ocr-eng tesseract-ocr-tur tesseract-ocr-deu fonts-liberation fonts-dejavu-core fonts-noto-core libssl-dev pkg-config"

        # Install dependencies
        sudo apt-get install -y $PACKAGES

        echo "Verifying Linux installations..."
        soffice --version
        tesseract --version
        echo "Verifying Tesseract language data..."
        tesseract --list-langs
        echo "Checking Tesseract data path..."
        if [ -d /usr/share/tesseract-ocr/5/tessdata ]; then
          echo "Found Tesseract 5 tessdata directory:"
          ls -la /usr/share/tesseract-ocr/5/tessdata/
          echo "Verifying required language files..."
          for lang in eng tur deu; do
            if [ ! -f "/usr/share/tesseract-ocr/5/tessdata/${lang}.traineddata" ]; then
              echo "ERROR: Missing required language file: ${lang}.traineddata" >&2
              exit 1
            else
              echo "✓ Found ${lang}.traineddata"
            fi
          done
        elif [ -d /usr/share/tesseract-ocr/tessdata ]; then
          echo "Found Tesseract tessdata directory:"
          ls -la /usr/share/tesseract-ocr/tessdata/
          echo "Verifying required language files..."
          for lang in eng tur deu; do
            if [ ! -f "/usr/share/tesseract-ocr/tessdata/${lang}.traineddata" ]; then
              echo "ERROR: Missing required language file: ${lang}.traineddata" >&2
              exit 1
            else
              echo "✓ Found ${lang}.traineddata"
            fi
          done
        else
          echo "ERROR: Tessdata directory not found in standard locations" >&2
          exit 1
        fi
        echo "Testing LibreOffice headless mode..."
        soffice --headless --version || echo "Warning: LibreOffice headless version check failed"

    - name: Cache Tesseract (Windows)
      if: runner.os == 'Windows'
      id: cache-tesseract-windows
      uses: actions/cache@v4
      with:
        path: C:\Program Files\Tesseract-OCR
        key: tesseract-data-${{ runner.os }}-v2
        restore-keys: |
          tesseract-data-${{ runner.os }}-

    - name: Cache LibreOffice (Windows)
      if: runner.os == 'Windows'
      id: cache-libreoffice-windows
      uses: actions/cache@v4
      with:
        path: C:\Program Files\LibreOffice
        key: libreoffice-${{ runner.os }}-v2

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # Check if tools are already cached
        $tesseractCacheHit = "${{ steps.cache-tesseract-windows.outputs.cache-hit }}" -eq "true"
        $libreofficeInstalled = Test-Path "C:\Program Files\LibreOffice\program\soffice.exe"

        # Build list of packages to install
        $packagesToInstall = @()

        if (-not $tesseractCacheHit) {
          Write-Host "Tesseract cache miss, adding to install list..."
          $packagesToInstall += "tesseract"
        } else {
          Write-Host "Tesseract found in cache, skipping installation"
        }

        if (-not $libreofficeInstalled) {
          Write-Host "LibreOffice not found, adding to install list..."
          $packagesToInstall += "libreoffice"
        } else {
          Write-Host "LibreOffice found in cache, skipping installation"
        }

        if ($packagesToInstall.Count -gt 0) {
          Write-Host "Installing packages from chocolatey: $($packagesToInstall -join ', ')..."
          choco install -y @packagesToInstall --no-progress
        } else {
          Write-Host "All packages found in cache, skipping installation"
        }

        Write-Output "C:\Program Files\LibreOffice\program" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output "C:\Program Files\Tesseract-OCR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "C:\Program Files\LibreOffice\program;C:\Program Files\Tesseract-OCR;" + $env:PATH

        # Install python-magic-bin for Windows compatibility
        python -m pip install python-magic-bin

        soffice --version
        tesseract --version
