name: Setup Python Environment
description: Install uv, set up Python, and cache the local virtual environment
inputs:
  python-version:
    description: Python version spec passed to actions/setup-python
    required: true
  cache-prefix:
    description: Prefix for cache keys
    required: false
    default: python-dependencies
outputs:
  python-version:
    description: Resolved Python version
    value: ${{ steps.setup-python.outputs.python-version }}
  cache-hit:
    description: Whether the dependency cache was restored
    value: ${{ steps.cache-python.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Compute uv.lock hash
      id: uv-lock-hash
      shell: bash
      run: |
        set -euo pipefail
        if [ -f uv.lock ]; then
          if command -v sha256sum >/dev/null 2>&1; then
            hash="$(sha256sum uv.lock | cut -d' ' -f1)"
          else
            hash="$(shasum -a 256 uv.lock | cut -d' ' -f1)"
          fi
        else
          echo "uv.lock not found, using fallback hash"
          hash="no-uv-lock"
        fi
        echo "value=$hash" >> "$GITHUB_OUTPUT"

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache Python dependencies
      id: cache-python
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ inputs.python-version }}-${{ steps.uv-lock-hash.outputs.value }}-v2
        restore-keys: |
          ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ inputs.python-version }}-v2-

    - name: Pin Python version for uv
      shell: bash
      run: |
        # Explicitly pin Python version to ensure uv uses the correct version
        uv python pin ${{ inputs.python-version }}

    - name: Install Python dependencies
      shell: bash
      run: |
        # Install workspace packages and all dev dependencies from root pyproject.toml
        uv sync --all-packages --all-groups --all-extras --no-install-project --no-install-workspace

        # Check if cv2 is broken (missing cvtColor attribute) and fix if needed
        # This can happen when opencv-contrib-python and opencv-python-headless conflict
        if ! uv run python -c "import cv2; assert hasattr(cv2, 'cvtColor')" 2>/dev/null; then
          echo "⚠️  Detected broken cv2 module, reinstalling OpenCV packages..."
          uv pip uninstall opencv-contrib-python opencv-python-headless --quiet 2>/dev/null || true
          uv pip install opencv-python-headless opencv-contrib-python
          echo "✅ OpenCV packages reinstalled"
        fi

    - name: Preserve PKG_CONFIG_PATH for OpenSSL
      shell: bash
      run: |
        if [ -n "${PKG_CONFIG_PATH:-}" ]; then
          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> "$GITHUB_ENV"
          echo "Preserved PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        fi
