
plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'lib/**/*.bundle'
    - 'ext/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'examples/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/SpecFilePathSuffix:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

RSpec/InstanceVariable:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  Max: 7
  Exclude:
    - 'lib/kreuzberg/config.rb'

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'lib/kreuzberg/config.rb'

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false
