name: Setup Static PDFium
description: Download and configure static PDFium libraries for pdf-static feature builds

inputs:
  pdfium-version:
    description: PDFium version to download
    required: true

runs:
  using: composite
  steps:
    - name: Detect platform and architecture
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        if [ "$OS" = "darwin" ]; then
          if [ "$ARCH" = "arm64" ]; then
            PLATFORM="macos-arm64"
          else
            PLATFORM="macos-x64"
          fi
        elif [ "$OS" = "linux" ]; then
          if [ "$ARCH" = "aarch64" ]; then
            PLATFORM="linux-arm64"
          else
            PLATFORM="linux-x64"
          fi
        elif [ "$OS" = "windows" ] || [[ "$OS" == *"mingw"* ]]; then
          PLATFORM="windows-x64"
        else
          echo "Unsupported platform: $OS"
          exit 1
        fi

        echo "PDFIUM_PLATFORM=$PLATFORM" >> $GITHUB_ENV

    - name: Cache static PDFium
      uses: actions/cache@v4
      with:
        path: ~/pdfium-static
        key: pdfium-static-v1-${{ env.PDFIUM_PLATFORM }}-${{ inputs.pdfium-version }}
        restore-keys: |
          pdfium-static-v1-${{ env.PDFIUM_PLATFORM }}-

    - name: Download static PDFium (if not cached)
      shell: bash
      run: |
        if [ ! -d ~/pdfium-static/lib ]; then
          mkdir -p ~/pdfium-static

          # Use PDFIUM_STATIC_VERSION env var, fallback to input
          STATIC_VERSION="${PDFIUM_STATIC_VERSION:-${{ inputs.pdfium-version }}}"

          # Map our platform names to bblanchon release asset names
          case "${{ env.PDFIUM_PLATFORM }}" in
            linux-x64)
              ASSET_NAME="pdfium-linux-x64.tgz"
              ;;
            linux-arm64)
              ASSET_NAME="pdfium-linux-arm64.tgz"
              ;;
            macos-x64)
              ASSET_NAME="pdfium-macos-x64.tgz"
              ;;
            macos-arm64)
              ASSET_NAME="pdfium-macos-arm64.tgz"
              ;;
            windows-x64)
              ASSET_NAME="pdfium-windows-x64.zip"
              ;;
            *)
              echo "ERROR: Unsupported platform ${{ env.PDFIUM_PLATFORM }}"
              exit 1
              ;;
          esac

          # Download from bblanchon/pdfium-binaries (has full platform support including Linux)
          URL="https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/${STATIC_VERSION}/${ASSET_NAME}"

          echo "Downloading static PDFium ${STATIC_VERSION} from: $URL"
          curl -fL --retry 5 --retry-delay 2 -o /tmp/pdfium-archive "$URL" || {
            echo "ERROR: Failed to download static PDFium from $URL"
            echo "Available versions: https://github.com/bblanchon/pdfium-binaries/releases"
            exit 1
          }

          # Extract (handles both .tgz and .zip)
          if [[ "$ASSET_NAME" == *.zip ]]; then
            unzip -q /tmp/pdfium-archive -d ~/pdfium-static || {
              echo "ERROR: Failed to extract PDFium archive"
              exit 1
            }
          else
            tar -xzf /tmp/pdfium-archive -C ~/pdfium-static || {
              echo "ERROR: Failed to extract PDFium archive"
              exit 1
            }
          fi
          rm /tmp/pdfium-archive

          if [ ! -f ~/pdfium-static/lib/libpdfium.a ]; then
            echo "ERROR: libpdfium.a not found after extraction"
            ls -la ~/pdfium-static/lib/ || echo "lib/ directory not found"
            exit 1
          fi

          echo "Static PDFium extracted successfully"
        else
          echo "Using cached static PDFium"
        fi

    - name: Export PDFIUM_STATIC_LIB_PATH
      shell: bash
      run: |
        echo "PDFIUM_STATIC_LIB_PATH=$HOME/pdfium-static/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$HOME/pdfium-static/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
