package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Text chunk generated by the chunking pipeline, with optional embedding vector.
 */
public final class Chunk {
    private final String content;
    private final List<Double> embedding;
    private final ChunkMetadata metadata;

    @JsonCreator
    public Chunk(
        @JsonProperty("content") String content,
        @JsonProperty("embedding") List<Double> embedding,
        @JsonProperty("metadata") ChunkMetadata metadata
    ) {
        this.content = Objects.requireNonNull(content, "content must not be null");
        this.metadata = Objects.requireNonNull(metadata, "metadata must not be null");
        if (embedding != null) {
            this.embedding = Collections.unmodifiableList(new ArrayList<>(embedding));
        } else {
            this.embedding = null;
        }
    }

    public String getContent() {
        return content;
    }

    public Optional<List<Double>> getEmbedding() {
        return embedding == null ? Optional.empty() : Optional.of(embedding);
    }

    public ChunkMetadata getMetadata() {
        return metadata;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Chunk)) {
            return false;
        }
        Chunk other = (Chunk) obj;
        return Objects.equals(content, other.content)
            && Objects.equals(embedding, other.embedding)
            && Objects.equals(metadata, other.metadata);
    }

    @Override
    public int hashCode() {
        return Objects.hash(content, embedding, metadata);
    }

    @Override
    public String toString() {
        return "Chunk{"
            + "contentLength=" + content.length()
            + ", embeddingDimensions=" + (embedding == null ? 0 : embedding.size())
            + ", metadata=" + metadata
            + '}';
    }
}
