name: Setup OpenSSL
description: Install and expose OpenSSL headers/libs across platforms
runs:
  using: composite
  steps:
    - name: Install OpenSSL (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev build-essential

        # Set environment variables for OpenSSL detection
        # On Ubuntu, OpenSSL is typically in /usr with pkgconfig in arch-specific path
        OPENSSL_ROOT="/usr"
        PKG_CONFIG_DIR="/usr/lib/x86_64-linux-gnu/pkgconfig"

        # Verify OpenSSL installation
        if [ ! -f "${PKG_CONFIG_DIR}/openssl.pc" ]; then
          echo "ERROR: openssl.pc not found at ${PKG_CONFIG_DIR}" >&2
          echo "Searching for openssl.pc..." >&2
          find /usr -name "openssl.pc" 2>/dev/null || true
          exit 1
        fi

        # Export environment variables
        {
          echo "OPENSSL_DIR=${OPENSSL_ROOT}"
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu"
          echo "OPENSSL_INCLUDE_DIR=/usr/include"
          echo "PKG_CONFIG_PATH=${PKG_CONFIG_DIR}:${PKG_CONFIG_PATH:-}"
        } >> "$GITHUB_ENV"

        echo "OpenSSL configuration completed:"
        echo "  OPENSSL_DIR=${OPENSSL_ROOT}"
        echo "  PKG_CONFIG_PATH=${PKG_CONFIG_DIR}"
        pkg-config --modversion openssl

    - name: Install OpenSSL (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -euo pipefail
        # Install packages only if not already present
        brew list openssl@3 &>/dev/null || brew install openssl
        brew list pkg-config &>/dev/null || brew install pkg-config
        prefix="$(brew --prefix openssl@3 2>/dev/null || brew --prefix openssl 2>/dev/null || true)"
        if [ -z "$prefix" ]; then
          echo "Failed to locate Homebrew OpenSSL prefix" >&2
          exit 1
        fi
        {
          echo "OPENSSL_DIR=$prefix"
          echo "OPENSSL_LIB_DIR=$prefix/lib"
          echo "OPENSSL_INCLUDE_DIR=$prefix/include"
          echo "PKG_CONFIG_PATH=$prefix/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
        } >> "$GITHUB_ENV"

    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install openssl -y
        $opensslDirs = @(
          "C:\Program Files\OpenSSL-Win64",
          "C:\Program Files\OpenSSL",
          "C:\ProgramData\chocolatey\lib\openssl\tools",
          "C:\Strawberry\c"
        )

        $selected = $null
        foreach ($dir in $opensslDirs) {
          if (Test-Path $dir) {
            $libPath = Join-Path $dir "lib"
            $includePath = Join-Path $dir "include"
            if ((Test-Path $libPath) -and (Test-Path $includePath)) {
              $selected = $dir
              break
            }
          }
        }

        if ($null -ne $selected) {
          Write-Host "Using OpenSSL at $selected"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_DIR=$selected"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_LIB_DIR=$selected\lib"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_INCLUDE_DIR=$selected\include"
        } else {
          Write-Host "OpenSSL not found in standard locations, installing via vcpkg..."
          vcpkg install openssl:x64-windows-static-md
          $vcpkgRoot = "C:\vcpkg\installed\x64-windows-static-md"
          if (-not (Test-Path $vcpkgRoot)) {
            Write-Error "vcpkg OpenSSL installation not found at $vcpkgRoot"
            exit 1
          }
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_DIR=$vcpkgRoot"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_LIB_DIR=$vcpkgRoot\lib"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_INCLUDE_DIR=$vcpkgRoot\include"
          Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_STATIC=1"
        }
