name: Smoke test Node package
description: Tests Node.js package installation and functionality

inputs:
  package-tarball:
    description: Path to the Node.js package tarball
    required: true

runs:
  using: composite
  steps:
    - name: Smoke Node install
      shell: bash
      run: |
        set -euo pipefail
        tarball="${{ inputs.package-tarball }}"
        # If directory provided, find the tarball inside
        if [[ -d "$tarball" ]]; then
          tarball=$(find "$tarball" -name "*.tgz" -type f | head -n 1)
          if [[ -z "$tarball" ]]; then
            echo "No .tgz file found in directory" >&2
            exit 1
          fi
        fi
        # Convert to absolute path before changing directories
        if [[ "$tarball" != /* ]]; then
          tarball="${GITHUB_WORKSPACE}/$tarball"
        fi
        echo "Using tarball: $tarball"
        tmp=$(mktemp -d)
        cp -R e2e/smoke/node/. "$tmp"/
        pushd "$tmp" >/dev/null
        cp "$tarball" ./kreuzberg-node.tgz
        node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));pkg.dependencies=pkg.dependencies||{};pkg.dependencies['kreuzberg-node']='file:./kreuzberg-node.tgz';fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+ '\n');"
        rm -f pnpm-lock.yaml
        pnpm install --no-frozen-lockfile
        pnpm run check
        popd >/dev/null
        echo "✓ Node package smoke test passed"
