name: Smoke test CLI binary
description: Tests Kreuzberg CLI binary installation and functionality

inputs:
  cli-artifacts-dir:
    description: Directory containing CLI binary artifacts
    required: true

runs:
  using: composite
  steps:
    - name: Smoke test CLI binary
      shell: bash
      run: |
        set -euo pipefail

        # Resolve to absolute path if relative
        if [[ "${{ inputs.cli-artifacts-dir }}" == /* ]]; then
          cli_artifacts_dir="${{ inputs.cli-artifacts-dir }}"
        else
          cli_artifacts_dir="${GITHUB_WORKSPACE}/${{ inputs.cli-artifacts-dir }}"
        fi

        echo "Looking for CLI artifacts in: $cli_artifacts_dir"
        ls -la "$cli_artifacts_dir" || true

        # Find the CLI archive for this platform
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cli_archive=$(find "$cli_artifacts_dir" -name "*.zip" -type f | head -n 1)
          if [ -z "$cli_archive" ]; then
            echo "CLI binary not found for Windows" >&2
            exit 1
          fi
          tmp=$(mktemp -d)
          unzip -q "$cli_archive" -d "$tmp"
          cli_bin=$(find "$tmp" -name "kreuzberg.exe" | head -n 1)
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          cli_archive=$(find "$cli_artifacts_dir" -name "*.tar.gz" -type f | head -n 1)
          if [ -z "$cli_archive" ]; then
            echo "CLI binary not found for macOS" >&2
            exit 1
          fi
          tmp=$(mktemp -d)
          tar -xzf "$cli_archive" -C "$tmp"
          cli_bin=$(find "$tmp" -name "kreuzberg" -type f | head -n 1)
        else
          cli_archive=$(find "$cli_artifacts_dir" -name "*.tar.gz" -type f | head -n 1)
          if [ -z "$cli_archive" ]; then
            echo "CLI binary not found for Linux" >&2
            exit 1
          fi
          tmp=$(mktemp -d)
          tar -xzf "$cli_archive" -C "$tmp"
          cli_bin=$(find "$tmp" -name "kreuzberg" -type f | head -n 1)
        fi

        if [ ! -f "$cli_bin" ]; then
          echo "ERROR: CLI binary extraction failed" >&2
          exit 1
        fi

        chmod +x "$cli_bin" || true

        # Test CLI with version command
        output=$("$cli_bin" --version)
        if ! echo "$output" | grep -q "kreuzberg"; then
          echo "ERROR: CLI did not produce expected version output" >&2
          echo "Output: $output" >&2
          exit 1
        fi

        echo "✓ CLI binary smoke test passed"
