#!/usr/bin/env pwsh
# Build Go bindings
# Used by: ci-go.yaml - Build Go bindings step
# Supports: Windows (MinGW), Unix (Linux/macOS)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$IsWindowsOS = $PSVersionTable.Platform -eq 'Win32NT' -or $PSVersionTable.PSVersion.Major -lt 6

cd packages/go/v4
$workspace = Resolve-Path "$PWD/../../.."

if ($IsWindowsOS) {
    Write-Host "=== Setting up Windows MinGW-w64 environment ==="
    $ffiPath = "$workspace/target/x86_64-pc-windows-gnu/release"

    # Validate FFI library exists before proceeding
    Write-Host "=== Pre-build validation ==="
    if (-not (Test-Path $ffiPath)) {
        Write-Error "FFI library path does not exist: $ffiPath" -ErrorAction Stop
    }

    $ffiLibraries = @(Get-ChildItem -Force "$ffiPath" -Filter "*kreuzberg_ffi*" -ErrorAction SilentlyContinue)
    if ($ffiLibraries.Count -eq 0) {
        Write-Error "No kreuzberg_ffi libraries found in: $ffiPath`nRun FFI build step (build-ffi.ps1) before building Go bindings." -ErrorAction Stop
    }

    Write-Host "Verified FFI libraries: $($ffiLibraries.Count) file(s) found"
    $ffiLibraries | ForEach-Object { Write-Host "  - $($_.Name)" }

    # MSYS2 UCRT64 toolchain is already available in PATH and CGO_LDFLAGS are
    # already configured by the CI workflow. We only need to ensure the library
    # path is in PATH for runtime discovery.
    $env:PATH = "$ffiPath;$env:PATH"

    Write-Host "=== Build Environment ==="
    Write-Host "FFI library path: $ffiPath"
    Write-Host "Libraries available:"
    Get-ChildItem -Force $ffiPath | findstr kreuzberg_ffi
    Write-Host "`nGCC version:"
    & gcc --version
    Write-Host "========================`n"
} else {
    $ffiPath = "$workspace/target/release"
    $pathSep = [System.IO.Path]::PathSeparator

    if ($env:LD_LIBRARY_PATH) {
        $env:LD_LIBRARY_PATH = "$ffiPath$pathSep$env:LD_LIBRARY_PATH"
    } else {
        $env:LD_LIBRARY_PATH = "$ffiPath"
    }

    if ($env:DYLD_LIBRARY_PATH) {
        $env:DYLD_LIBRARY_PATH = "$ffiPath$pathSep$env:DYLD_LIBRARY_PATH"
    } else {
        $env:DYLD_LIBRARY_PATH = "$ffiPath"
    }

    # Ensure pkg-config can find the dev .pc file generated by crates/kreuzberg-ffi/build.rs
    $devPcDir = "$workspace/crates/kreuzberg-ffi"
    if ($env:PKG_CONFIG_PATH) {
        $env:PKG_CONFIG_PATH = "$devPcDir$pathSep$env:PKG_CONFIG_PATH"
    } else {
        $env:PKG_CONFIG_PATH = "$devPcDir"
    }
}

# Try build normally first, use -x flag on failure for diagnostics
if (-not (go build -v ./...)) {
    Write-Host "`n=== Build failed, retrying with verbose CGO diagnostics ==="
    go build -x -v ./...
}
