name: Setup Prebuilt ONNX Runtime
description: Download prebuilt ONNX Runtime static libraries for Apple targets
inputs:
  target:
    description: Target triple determining which archive to download
    required: true
runs:
  using: composite
  steps:
    - name: Prepare ONNX Runtime archive
      shell: bash
      run: |
        set -euo pipefail
        target="${{ inputs.target }}"
        case "$target" in
          aarch64-apple-darwin)
            ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.23.2/aarch64-apple-darwin.tgz"
            ;;
          x86_64-apple-darwin)
            ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.23.2/x86_64-apple-darwin.tgz"
            ;;
          *)
            echo "setup-prebuilt-onnx does not support target $target" >&2
            exit 1
            ;;
        esac

        ort_dir="${RUNNER_TEMP}/onnxruntime/${target}"
        ort_root="${ort_dir}/onnxruntime"
        ort_lib="${ort_root}/lib"
        if [ ! -f "${ort_lib}/libonnxruntime.a" ]; then
          rm -rf "${ort_dir}"
          mkdir -p "${ort_lib}"
          curl -fsSL "${ort_url}" | tar -xz -C "${ort_lib}"
        fi

        {
          echo "ORT_STRATEGY=system"
          echo "ORT_LIB_LOCATION=${ort_lib}"
          echo "ORT_SKIP_DOWNLOAD=1"
          echo "ORT_PREFER_DYNAMIC_LINK=1"
        } >> "${GITHUB_ENV}"
