name: Setup Prebuilt ONNX Runtime
description: Download prebuilt ONNX Runtime static libraries for Apple targets
inputs:
  target:
    description: Target triple determining which archive to download
    required: true
runs:
  using: composite
  steps:
    - name: Prepare ONNX Runtime archive
      shell: bash
      run: |
        set -euo pipefail
        target="${{ inputs.target }}"
        case "$target" in
          aarch64-apple-darwin)
            ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.23.2/aarch64-apple-darwin.tgz"
            ;;
          x86_64-apple-darwin)
            ort_url="https://cdn.pyke.io/0/pyke:ort-rs/ms@1.23.2/x86_64-apple-darwin.tgz"
            ;;
          *)
            echo "setup-prebuilt-onnx does not support target $target" >&2
            exit 1
            ;;
        esac

        ort_dir="${GITHUB_WORKSPACE}/target/onnxruntime/${target}"
        ort_root="${ort_dir}/onnxruntime"
        ort_lib="${ort_root}/lib"

        if [ ! -f "${ort_lib}/libonnxruntime.a" ]; then
          rm -rf "${ort_dir}"
          mkdir -p "${ort_lib}"

          # Try to download prebuilt ONNX Runtime from CDN
          echo "Attempting to download prebuilt ONNX Runtime for ${target}..."
          if curl -fsSL --max-time 30 -o /tmp/ort.tgz "${ort_url}" 2>/dev/null; then
            echo "Successfully downloaded ONNX Runtime archive"
            tar -xz -C "${ort_lib}" -f /tmp/ort.tgz
            rm -f /tmp/ort.tgz

            {
              echo "ORT_STRATEGY=system"
              echo "ORT_LIB_LOCATION=${ort_lib}"
              echo "ORT_SKIP_DOWNLOAD=1"
              echo "ORT_PREFER_DYNAMIC_LINK=1"
            } >> "${GITHUB_ENV}"
          else
            echo "Warning: Prebuilt ONNX Runtime not available for ${target}"
            echo "Will download and build ONNX Runtime during compilation"
            # Don't set ORT env vars, let ort-rs handle the download and build
          fi
        else
          echo "Using existing ONNX Runtime at ${ort_lib}"
          {
            echo "ORT_STRATEGY=system"
            echo "ORT_LIB_LOCATION=${ort_lib}"
            echo "ORT_SKIP_DOWNLOAD=1"
            echo "ORT_PREFER_DYNAMIC_LINK=1"
          } >> "${GITHUB_ENV}"
        fi
