// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// Category: html

package e2e

import "testing"

func TestHTML_HTML_COMPLEX_LAYOUT(t *testing.T) {
    result := runExtraction(t, "web/taylor_swift.html", nil)
    assertExpectedMime(t, result, []string{"text/html"})
    assertMinContentLength(t, result, 1000)
}

func TestHTML_HTML_SIMPLE_TABLE(t *testing.T) {
    result := runExtraction(t, "web/simple_table.html", nil)
    assertExpectedMime(t, result, []string{"text/html"})
    assertMinContentLength(t, result, 20)
    assertContentContainsAll(t, result, []string{"|"})
}

