name: Setup Maven 3.9.12
description: Install Maven 3.9.12 in a cross-platform way
runs:
  using: composite
  steps:
    - name: Setup Maven 3.9.12
      shell: bash
      run: |
        MAVEN_VERSION="3.9.12"
        MAVEN_URL="https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"

        # Use a temp directory that works across platforms
        TEMP_DIR="$(pwd)/maven-temp"
        mkdir -p "$TEMP_DIR"

        curl -fsSL "$MAVEN_URL" -o "$TEMP_DIR/maven.tar.gz"
        tar -xzf "$TEMP_DIR/maven.tar.gz" -C "$TEMP_DIR"

        MAVEN_HOME="$TEMP_DIR/apache-maven-${MAVEN_VERSION}"
        echo "$MAVEN_HOME/bin" >> "$GITHUB_PATH"

        # Verify Maven version
        "$MAVEN_HOME/bin/mvn" --version
